name: weather
description: ""
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher.png"
  adaptive_icon_background: "#2162C2"
  adaptive_icon_foreground: "assets/icons/launcher.png"

flutter_native_splash:
  color: "#2162C2"
  android_12:
    color: "#2162C2"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env
